import libs = nlohmann-json%lib{json}

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript{**}

if($cxx.class != 'msvc')
{
    cxx.coptions += -Wno-unused-comparison -Wno-unused-result -Wno-unused-variable  # Ignore warnings for now.
}

