int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

lib{json}: include/hxx{**} $imp_libs $int_libs

# Build options.
#
cxx.poptions =+ "-I$src_base/include" "-I$out_base/include"

# Export options.
#
lib{json}:
{
  cxx.export.poptions =  "-I$src_base/include" "-I$out_base/include"
  cxx.export.libs = $int_libs
}

# Install into the json/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
